import React, { useState } from "react";
import {
  StyledContainer,
  StyledNavbar,
  FileListContainer
} from "./Dashboard.styles.js";
import {
  InboxOutlined,
  FileExcelOutlined,
  DeleteOutlined
} from "@ant-design/icons";
import {
  message,
  Upload,
  Button,
  List,
  Card,
  Table,
  Typography,
  Spin
} from "antd";

const { Dragger } = Upload;
const { Title, Paragraph } = Typography;

const dummyOutput = {
  summary:
    "Your document was processed successfully. Summary was extracted and structured.",
  htmlPreview: `
    <h3>Processed Report Preview</h3>
    <p>This is a <b>dummy visual preview</b> of the processed file generated by the workflow.</p>
    <ul>
      <li>Extracted 12 key points</li>
      <li>Detected 2 tables</li>
      <li>Found 1 chart</li>
    </ul>
  `,
  table: [
    { name: "John Doe", score: 92, status: "Pass" },
    { name: "Alice Smith", score: 88, status: "Pass" },
    { name: "Bob Khan", score: 59, status: "Fail" }
  ]
};

const dummyDownloadUrl =
  "https://filesamples.com/samples/document/docx/sample1.docx";

const ProcessedOutput = ({ output, downloadUrl }) => {
  if (!output) return null;

  return (
    <div style={{ marginTop: "2rem" }}>
      <Card
        title="Workflow Output"
        style={{
          borderRadius: "12px",
          boxShadow: "0 4px 14px rgba(0,0,0,0.1)"
        }}
      >
        <Title level={4}>Summary</Title>
        <Paragraph>{output.summary}</Paragraph>

        {output.htmlPreview && (
          <>
            <Title level={4}>Preview</Title>
            <div
              dangerouslySetInnerHTML={{ __html: output.htmlPreview }}
              style={{
                background: "#fafafa",
                padding: "1rem",
                borderRadius: "8px",
                marginBottom: "1rem"
              }}
            />
          </>
        )}

        {output.table && (
          <>
            <Title level={4}>Extracted Table</Title>
            <Table
              dataSource={output.table}
              rowKey="name"
              columns={Object.keys(output.table[0]).map((key) => ({
                title: key.toUpperCase(),
                dataIndex: key,
                key
              }))}
              bordered
              pagination={false}
            />
          </>
        )}

        <Button
          type="primary"
          href={downloadUrl}
          download
          style={{ marginTop: "2rem" }}
        >
          Download Processed Word File
        </Button>
      </Card>
    </div>
  );
};

const Dashboard = () => {
  const [fileList, setFileList] = useState([]);
  const [output, setOutput] = useState(null);
  const [downloadUrl, setDownloadUrl] = useState(null);
  const [loading, setLoading] = useState(false);

  const props = {
    name: "file",
    multiple: true,
    accept: ".xls,.xlsx,.pdf,.docx",
    customRequest: async ({ file, onSuccess, onError }) => {
      try {
        setLoading(true);
        await new Promise((resolve) => setTimeout(resolve, 3000));
        setOutput(dummyOutput);
        setDownloadUrl(dummyDownloadUrl);
        onSuccess("ok");
        message.success(`${file.name} processed successfully.`);
      } catch (err) {
        console.error(err);
        onError(err);
        message.error(`${file.name} processing failed.`);
      } finally {
        setLoading(false);
      }
    },
    fileList,
    onChange(info) {
      let newList = [...info.fileList];
      setFileList(newList);
    },
    onDrop(e) {
      console.log("Dropped files", e.dataTransfer.files);
    }
  };

  const clearFiles = () => {
    setFileList([]);
    setOutput(null);
    setDownloadUrl(null);
    message.info("All files cleared.");
  };

  return (
    <>
      <StyledNavbar>
        <h2>Excel Dashboard</h2>
        <Button
          type="primary"
          danger
          icon={<DeleteOutlined />}
          onClick={clearFiles}
        >
          Clear All
        </Button>
      </StyledNavbar>

      <StyledContainer>
        <Dragger
          {...props}
          style={{
            padding: "2rem",
            borderRadius: "12px",
            boxShadow: "0 4px 12px rgba(0,0,0,0.1)"
          }}
        >
          <p className="ant-upload-drag-icon">
            <InboxOutlined style={{ fontSize: "32px", color: "#1890ff" }} />
          </p>
          <p className="ant-upload-text">Click or drag files to upload</p>
          <p className="ant-upload-hint">Only .xls,.xlsx,.pdf, .docx files.</p>
        </Dragger>

        {fileList.length > 0 && (
          <FileListContainer>
            <h3>Uploaded Files</h3>
            <List
              bordered
              dataSource={fileList}
              renderItem={(file) => (
                <List.Item
                  actions={[
                    <span>{(file.size / 1024).toFixed(2)} KB</span>,
                    <span>{file.status}</span>
                  ]}
                >
                  <FileExcelOutlined
                    style={{ color: "#52c41a", marginRight: "8px" }}
                  />
                  {file.name}
                </List.Item>
              )}
            />
          </FileListContainer>
        )}

        {loading && (
          <div style={{ textAlign: "center", margin: "2rem 0" }}>
            <Spin size="large" tip="Processing workflow..." />
          </div>
        )}

        {!loading && output && (
          <ProcessedOutput output={output} downloadUrl={downloadUrl} />
        )}
      </StyledContainer>
    </>
  );
};

export default Dashboard;
